//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int id { get; set; }
        public string tenSPHD { get; set; }
        public string SLMua { get; set; }
        public System.DateTime DateMua { get; set; }
    }
}
